### ISSUE TITLE
encounter an error when loading realisticVisionV60B1_v51VAE.safetensors

### ISSUE THREAD

**Issue by qwer1234a404** [Bujiazi/MotionClone#19]
load dreambooth model from models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors
Traceback (most recent call last):
  File "/home/tione/notebook/lskong2/softwares1/MotionClone/i2v_video_sample.py", line 157, in <module>
    main(args)
  File "/home/tione/notebook/lskong2/softwares1/MotionClone/i2v_video_sample.py", line 71, in main
    pipeline = load_weights(
  File "/home/tione/notebook/lskong2/softwares1/MotionClone/motionclone/utils/util.py", line 159, in load_weights
    animation_pipeline.vae.load_state_dict(converted_vae_checkpoint)
  File "/home/tione/notebook/lskong2/softwares/anaconda3/envs/dsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
	Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias". 
	Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.value.weight".

**Comment by LPengYang** [comment]
> load dreambooth model from models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors Traceback (most recent call last): File "/home/tione/notebook/lskong2/softwares1/MotionClone/i2v_video_sample.py", line 157, in main(args) File "/home/tione/notebook/lskong2/softwares1/MotionClone/i2v_video_sample.py", line 71, in main pipeline = load_weights( File "/home/tione/notebook/lskong2/softwares1/MotionClone/motionclone/utils/util.py", line 159, in load_weights animation_pipeline.vae.load_state_dict(converted_vae_checkpoint) File "/home/tione/notebook/lskong2/softwares/anaconda3/envs/dsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for AutoencoderKL: Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias". Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.value.weight".

Hi~, What is the size of the loaded file of "realisticVisionV60B1_v51VAE.safetensors"?  The file is expected to be 2.0GB.  Maybe re-downloading help?

**Comment by tyrink** [comment]
Same question. The size of the loaded file of "realisticVisionV60B1_v51VAE.safetensors" is 1.99GB
