### ISSUE TITLE
Release time estimate

### ISSUE THREAD

**Issue by voku682** [Bujiazi/MotionClone#2]
Hey guys, it's been about two weeks, can you all give any estimate on when the code will be released ? (sorry for being impatient 😅)

**Comment by Bujiazi** [comment]
We sincerely apologize for the delay 😂. We are currently organizing the project code and expect to open source the MotionClone code later this week.

**Comment by Bujiazi** [comment]
Hello, thanks for your attention to MotionClone. We have released the first version of our code now. 😄
