### ISSUE TITLE
Why input null-text when generating ref video's guidance?

### ISSUE THREAD

**Issue by hrcheng98** [Bujiazi/MotionClone#20]
![image](https://github.com/user-attachments/assets/a3c8c062-68fb-4e0e-ab54-7b59d03cf417)

Previous work(VMC) used simplified prompts (like 'A boy is running') to distill motion guidance. Have you tried something like this?

**Comment by LPengYang** [comment]
> ![image](https://private-user-images.githubusercontent.com/35272101/378218384-a3c8c062-68fb-4e0e-ab54-7b59d03cf417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Nzc2MjIsIm5iZiI6MTcyOTQ3NzMyMiwicGF0aCI6Ii8zNTI3MjEwMS8zNzgyMTgzODQtYTNjOGMwNjItNjhmYi00ZTBlLWFiNTQtN2I1OWQwM2NmNDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAyMjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlN2FmZDBiMDk1NGRhNDE3MTg3NDhmMDJjNjBjZjcxMGEyMGM4NGMzZWNkMjJmMDBlYmU0YTU1OTI3Y2M0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gBfqIzNuvZ7VKATdoYvMZha334m0bSvybJLTsqMfV_E)
> 
> Previous work(VMC) used simplified prompts (like 'A boy is running') to distill motion guidance. Have you tried something like this?
Thanks for your attention on our work! Precise prompt tailored for reference video also works in our work. However, from a user-friendly perspective, we adopt null-text as the default setting, allowing users to provide reference motion by simply offering a reference video. In our experiments，few differences arise when using tailored prompts regrading video content，We speculate that motion-related information is effective preserved in diffusion features at time step of 400, thereby diminishing the significance of the precise prompt. More details are avaiable on the ablation study of the updated paper.
