### ISSUE TITLE
Pip subprocess error: ERROR: Could not find a version that satisfies the requirement triton (from versions: none) ERROR: No matching distribution found for triton  failed  CondaEnvException: Pip failed

### ISSUE THREAD

**Issue by brad12d3** [Bujiazi/MotionClone#7]
Getting this error

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton

failed

CondaEnvException: Pip failed

**Comment by Bujiazi** [comment]
Thanks for the feedback. Please provide more information about your operating platform, Python version, and other relevant details to help us identify the issue (We conduct our experiments on a **Linux** server with **CUDA 11.8** and **Python 3.11.3**).

**Comment by djbielejeski** [comment]
On windows I had to manually install all of the pip dependencies, and for triton I downloaded the pre-compiled whl `triton-2.1.0-cp311-cp311-win_amd64.whl` from here: https://huggingface.co/madbuda/triton-windows-builds/tree/main and installed with

`pip install /path-to-whl/triton-2.1.0-cp311-cp311-win_amd64.whl`

**Comment by Bujiazi** [comment]
Thank you for your response 🌹. Since a satisfactory response has been provided, we are now closing this issue. If needed, we can reopen it in the future.
